import { slugify } from "@/lib/slug/slugify";

export type NormalizedCategory = {
  name: string;
  slug: string;
};

const CATEGORY_PAIRS = [
  ["2-players-games", "2 Kişilik Oyunlar", "2-kisilik-oyunlar"],
  ["3d-games", "3D Oyunlar", "3d-oyunlar"],
  ["action", "Aksiyon Oyunları", "aksiyon-oyunlari"],
  ["aksiyon", "Aksiyon Oyunları", "aksiyon-oyunlari"],
  ["action-games", "Aksiyon Oyunları", "aksiyon-oyunlari"],
  ["adventure-games", "Macera Oyunları", "macera-oyunlari"],
  ["against-time-games", "Zamana Karşı Oyunlar", "zamana-karsi-oyunlar"],
  ["aim-shoot-game", "Atış Oyunları", "atis-oyunlari"],
  ["alien-games", "Uzaylı Oyunları", "uzayli-oyunlari"],
  ["angry-birds-games", "Angry Birds Oyunları", "angry-birds-oyunlari"],
  ["animal-games", "Hayvan Oyunları", "hayvan-oyunlari"],
  ["animation-games", "Animasyon Oyunları", "animasyon-oyunlari"],
  ["anime-and-manga-games", "Anime ve Manga Oyunları", "anime-ve-manga-oyunlari"],
  ["avoid-games", "Kaçınma Oyunları", "kacinma-oyunlari"],
  ["baby-games", "Bebek Oyunları", "bebek-oyunlari"],
  ["bakugan-games", "Bakugan Oyunları", "bakugan-oyunlari"],
  ["balance-games", "Denge Oyunları", "denge-oyunlari"],
  ["balloon-games", "Balon Oyunları", "balon-oyunlari"],
  ["barbie-games", "Barbie Oyunları", "barbie-oyunlari"],
  ["batman-games", "Batman Oyunları", "batman-oyunlari"],
  ["battle-games", "Savaş Oyunları", "savas-oyunlari"],
  ["beauty-games", "Güzellik Oyunları", "guzellik-oyunlari"],
  ["ben-10-games", "Ben 10 Oyunları", "ben-10-oyunlari"],
  ["bike-games", "Bisiklet Oyunları", "bisiklet-oyunlari"],
  ["bloody-games", "Kanlı Oyunlar", "kanli-oyunlar"],
  ["blow-up-games", "Patlatma Oyunları", "patlatma-oyunlari"],
  ["board-games", "Masa Oyunları", "masa-oyunlari"],
  ["boat-games", "Tekne Oyunları", "tekne-oyunlari"],
  ["bomb-games", "Bomba Oyunları", "bomba-oyunlari"],
  ["bow-and-arrow-games", "Ok ve Yay Oyunları", "ok-ve-yay-oyunlari"],
  ["building-games", "İnşa Etme Oyunları", "insa-etme-oyunlari"],
  ["car-games", "Araba Oyunları", "araba-oyunlari"],
  ["card-games", "Kart Oyunları", "kart-oyunlari"],
  ["caring-games", "Bakım Oyunları", "bakim-oyunlari"],
  ["cars", "Araba Oyunları", "araba-oyunlari"],
  ["arabalar", "Araba Oyunları", "araba-oyunlari"],
  ["castle-games", "Kale Oyunları", "kale-oyunlari"],
  ["chess-games", "Satranç Oyunları", "satranc-oyunlari"],
  ["christmas-games", "Noel Oyunları", "noel-oyunlari"],
  ["classic-games", "Klasik Oyunlar", "klasik-oyunlar"],
  ["collections", "Oyun Koleksiyonları", "oyun-koleksiyonlari"],
  ["koleksiyonlar", "Oyun Koleksiyonları", "oyun-koleksiyonlari"],
  ["coloring-games", "Boyama Oyunları", "boyama-oyunlari"],
  ["comb-games", "Tarak Oyunları", "tarak-oyunlari"],
  ["cooking-games", "Yemek Oyunları", "yemek-oyunlari"],
  ["cow-games", "İnek Oyunları", "inek-oyunlari"],
  ["crab-games", "Yengeç Oyunları", "yengec-oyunlari"],
  ["curiosities", "İlginç Oyunlar", "ilginc-oyunlar"],
  ["cutting-games", "Kesme Oyunları", "kesme-oyunlari"],
  ["dance-games", "Dans Oyunları", "dans-oyunlari"],
  ["defense-games", "Savunma Oyunları", "savunma-oyunlari"],
  ["destruction", "Yıkım Oyunları", "yikim-oyunlari"],
  ["yikim", "Yıkım Oyunları", "yikim-oyunlari"],
  ["destruction-games", "Yıkım Oyunları", "yikim-oyunlari"],
  ["detective-games", "Dedektif Oyunları", "dedektif-oyunlari"],
  ["difference-games", "Fark Bulma Oyunları", "fark-bulma-oyunlari"],
  ["dinosaur-games", "Dinozor Oyunları", "dinozor-oyunlari"],
  ["doctor-games", "Doktor Oyunları", "doktor-oyunlari"],
  ["doll-games", "Oyuncak Bebek Oyunları", "oyuncak-bebek-oyunlari"],
  ["dragon-ball-games", "Dragon Ball Oyunları", "dragon-ball-oyunlari"],
  ["dragon-games", "Ejderha Oyunları", "ejderha-oyunlari"],
  ["dress-up-games", "Giydirme Oyunları", "giydirme-oyunlari"],
  ["escape-games", "Kaçış Oyunları", "kacis-oyunlari"],
  ["famous-games", "Ünlü Oyunları", "unlu-oyunlari"],
  ["fantasy-games", "Fantastik Oyunlar", "fantastik-oyunlar"],
  ["farm-games", "Çiftlik Oyunları", "ciftlik-oyunlari"],
  ["fashion-games", "Moda Oyunları", "moda-oyunlari"],
  ["fighting-games", "Dövüş Oyunları", "dovus-oyunlari"],
  ["food-games", "Yemek Oyunları", "yemek-oyunlari"],
  ["football-games", "Futbol Oyunları", "futbol-oyunlari"],
  ["formula-1-games", "Formula 1 Oyunları", "formula-1-oyunlari"],
  ["game-collections", "Oyun Koleksiyonları", "oyun-koleksiyonlari"],
  ["game-pieces", "Oyun Parçaları", "oyun-parcalari"],
  ["games", "Oyunlar", "oyunlar"],
  ["games-with-walkthroughs", "Çözüm Videolu Oyunlar", "cozum-videolu-oyunlar"],
  ["goku-games", "Goku Oyunları", "goku-oyunlari"],
  ["halloween-games", "Cadılar Bayramı Oyunları", "cadilar-bayrami-oyunlari"],
  ["helicopter-games", "Helikopter Oyunları", "helikopter-oyunlari"],
  ["hidden-object-games", "Gizli Nesne Oyunları", "gizli-nesne-oyunlari"],
  ["hockey-games", "Hokey Oyunları", "hokey-oyunlari"],
  ["jump-games", "Zıplama Oyunları", "ziplama-oyunlari"],
  ["kart-games", "Karting Oyunları", "karting-oyunlari"],
  ["kids-games", "Çocuk Oyunları", "cocuk-oyunlari"],
  ["kitchen-games", "Mutfak Oyunları", "mutfak-oyunlari"],
  ["logic-games", "Mantık Oyunları", "mantik-oyunlari"],
  ["make-up-games", "Makyaj Oyunları", "makyaj-oyunlari"],
  ["management-games", "Yönetim Oyunları", "yonetim-oyunlari"],
  ["mario-bros-games", "Mario Bros Oyunları", "mario-bros-oyunlari"],
  ["math-games", "Matematik Oyunları", "matematik-oyunlari"],
  ["memory-games", "Hafıza Oyunları", "hafiza-oyunlari"],
  ["metal-slug-games", "Metal Slug Oyunları", "metal-slug-oyunlari"],
  ["mini-golf-games", "Mini Golf Oyunları", "mini-golf-oyunlari"],
  ["missile-games", "Füze Oyunları", "fuze-oyunlari"],
  ["monster-game", "Canavar Oyunları", "canavar-oyunlari"],
  ["monster-truck-games", "Canavar Kamyon Oyunları", "canavar-kamyon-oyunlari"],
  ["motocross-games", "Motokros Oyunları", "motokros-oyunlari"],
  ["motorbike-games", "Motosiklet Oyunları", "motosiklet-oyunlari"],
  ["motorboat-games", "Tekne Oyunları", "tekne-oyunlari"],
  ["mouse-games", "Fare Oyunları", "fare-oyunlari"],
  ["movie-games", "Film Oyunları", "film-oyunlari"],
  ["multiplayer-games", "Çok Oyunculu Oyunlar", "cok-oyunculu-oyunlar"],
  ["munecas", "Bebek Giydirme Oyunları", "bebek-giydirme-oyunlari"],
  ["murder-games", "Cinayet Oyunları", "cinayet-oyunlari"],
  ["music-games", "Müzik Oyunları", "muzik-oyunlari"],
  ["mystery-games", "Gizem Oyunları", "gizem-oyunlari"],
  ["naruto-games", "Naruto Oyunları", "naruto-oyunlari"],
  ["ninja-games", "Ninja Oyunları", "ninja-oyunlari"],
  ["ninja-turtles-games", "Ninja Kaplumbağalar Oyunları", "ninja-kaplumbagalar-oyunlari"],
  ["parking-games", "Park Etme Oyunları", "park-etme-oyunlari"],
  ["pedicure-games", "Pedikür Oyunları", "pedikur-oyunlari"],
  ["physics-games", "Fizik Oyunları", "fizik-oyunlari"],
  ["pick-up-games", "Toplama Oyunları", "toplama-oyunlari"],
  ["pinball-games", "Pinball Oyunları", "pinball-oyunlari"],
  ["platform-games", "Platform Oyunları", "platform-oyunlari"],
  ["point-and-click-games", "Tıkla ve Oyna Oyunları", "tikla-ve-oyna-oyunlari"],
  ["pokemon-games", "Pokemon Oyunları", "pokemon-oyunlari"],
  ["police-games", "Polis Oyunları", "polis-oyunlari"],
  ["power-rangers-games", "Power Rangers Oyunları", "power-rangers-oyunlari"],
  ["punching-games", "Yumruk Oyunları", "yumruk-oyunlari"],
  ["puzzle-and-skill-games", "Bulmaca ve Beceri Oyunları", "bulmaca-ve-beceri-oyunlari"],
  ["quad-games", "ATV Oyunları", "atv-oyunlari"],
  ["racing-games", "Yarış Oyunları", "yaris-oyunlari"],
  ["restaurant-games", "Restoran Oyunları", "restoran-oyunlari"],
  ["ritmo-games", "Ritim Oyunları", "ritim-oyunlari"],
  ["robot-games", "Robot Oyunları", "robot-oyunlari"],
  ["role-playing-games", "Rol Yapma Oyunları", "rol-yapma-oyunlari"],
  ["running-games", "Koşu Oyunları", "kosu-oyunlari"],
  ["santa-claus-games", "Noel Baba Oyunları", "noel-baba-oyunlari"],
  ["season-games", "Mevsim Oyunları", "mevsim-oyunlari"],
  ["ship-games", "Gemi Oyunları", "gemi-oyunlari"],
  ["shooting-games", "Atış Oyunları", "atis-oyunlari"],
  ["shopping-games", "Alışveriş Oyunları", "alisveris-oyunlari"],
  ["simulation-games", "Simülasyon Oyunları", "simulasyon-oyunlari"],
  ["skate-games", "Kaykay Oyunları", "kaykay-oyunlari"],
  ["skill-games", "Beceri Oyunları", "beceri-oyunlari"],
  ["solitaire-games", "Solitaire Oyunları", "solitaire-oyunlari"],
  ["speed-games", "Hız Oyunları", "hiz-oyunlari"],
  ["spongebob-games", "SpongeBob Oyunları", "spongebob-oyunlari"],
  ["sport-games", "Spor Oyunları", "spor-oyunlari"],
  ["star-wars-games", "Star Wars Oyunları", "star-wars-oyunlari"],
  ["stickman-games", "Stickman Oyunları", "stickman-oyunlari"],
  ["story-games", "Hikaye Oyunları", "hikaye-oyunlari"],
  ["strategy-games", "Strateji Oyunları", "strateji-oyunlari"],
  ["stunt-games", "Akrobasi Oyunları", "akrobasi-oyunlari"],
  ["superhero-games", "Süper Kahraman Oyunları", "super-kahraman-oyunlari"],
  ["surfing-games", "Sörf Oyunları", "sorf-oyunlari"],
  ["surgery-games", "Ameliyat Oyunları", "ameliyat-oyunlari"],
  ["sword-games", "Kılıç Oyunları", "kilic-oyunlari"],
  ["tank-games", "Tank Oyunları", "tank-oyunlari"],
  ["the-simpsons-games", "Simpsons Oyunları", "simpsons-oyunlari"],
  ["thinking-games", "Düşünme Oyunları", "dusunme-oyunlari"],
  ["throwing-games", "Fırlatma Oyunları", "firlatma-oyunlari"],
  ["time-games", "Zaman Oyunları", "zaman-oyunlari"],
  ["tommy-gun-games", "Tommy Gun Oyunları", "tommy-gun-oyunlari"],
  ["turn-based-games", "Sıra Tabanlı Oyunlar", "sira-tabanli-oyunlar"],
  ["tv-serie-games", "Dizi Oyunları", "dizi-oyunlari"],
  ["violent-games", "Şiddet Oyunları", "siddet-oyunlari"],
  ["war-games", "Savaş Oyunları", "savas-oyunlari"],
  ["savas-temali-oyunlar", "Savaş Oyunları", "savas-oyunlari"],
  ["weapon-games", "Silah Oyunları", "silah-oyunlari"],
  ["world-war-games", "Dünya Savaşı Oyunları", "dunya-savasi-oyunlari"],
  ["wrestling-games", "Güreş Oyunları", "gures-oyunlari"],
  ["zombie-games", "Zombi Oyunları", "zombi-oyunlari"],
  ["browser-game", "Tarayıcı Oyunları", "tarayici-oyunlari"],
  ["browser-games", "Tarayıcı Oyunları", "tarayici-oyunlari"],
  ["browser", "Tarayıcı Oyunları", "tarayici-oyunlari"],
  ["4x4-games", "4x4 Oyunları", "4x4-oyunlari"],
  ["ball-games", "Top Oyunları", "top-oyunlari"],
  ["bear-games", "Ayı Oyunları", "ayi-oyunlari"],
  ["billiards-games", "Bilardo Oyunları", "bilardo-oyunlari"],
  ["bomberman-games", "Bomberman Oyunları", "bomberman-oyunlari"],
  ["causality-games", "Sebep Sonuç Oyunları", "sebep-sonuc-oyunlari"],
  ["doraemon-games", "Doraemon Oyunları", "doraemon-oyunlari"],
  ["funny-games", "Komik Oyunlar", "komik-oyunlar"],
  ["hairdresser-games", "Kuaför Oyunları", "kuafor-oyunlari"],
  ["mobile-games", "Mobil Oyunlar", "mobil-oyunlar"],
  ["one-piece-games", "One Piece Oyunları", "one-piece-oyunlari"],
  ["painting-games", "Resim Yapma Oyunları", "resim-yapma-oyunlari"],
  ["penalty-games", "Penaltı Oyunları", "penalti-oyunlari"],
  ["pirate-games", "Korsan Oyunları", "korsan-oyunlari"],
  ["sara-games", "Sara Oyunları", "sara-oyunlari"],
  ["sheep-games", "Koyun Oyunları", "koyun-oyunlari"],
  ["singer-games", "Şarkıcı Oyunları", "sarkici-oyunlari"],
  ["snow-games", "Kar Oyunları", "kar-oyunlari"],
  ["stabilize-games", "Denge Oyunları", "denge-oyunlari"],
  ["nisan-ve-atis-oyunlari", "Atış Oyunları", "atis-oyunlari"],
  ["yemek-yapma-oyunlari", "Yemek Oyunları", "yemek-oyunlari"],
  ["motorlu-tekne-oyunlari", "Tekne Oyunları", "tekne-oyunlari"],
  ["dengeleme-oyunlari", "Denge Oyunları", "denge-oyunlari"],
  ["survival-games", "Hayatta Kalma Oyunları", "hayatta-kalma-oyunlari"],
  ["tower-defense-games", "Kule Savunma Oyunları", "kule-savunma-oyunlari"],
  ["transformers-games", "Transformers Oyunları", "transformers-oyunlari"],
  ["wolf-games", "Kurt Oyunları", "kurt-oyunlari"],
] as const;

const DEFAULT_CATEGORY: NormalizedCategory = { name: "Oyunlar", slug: "oyunlar" };

const CATEGORY_MAP = new Map<string, NormalizedCategory>();

for (const [sourceSlug, name, slug] of CATEGORY_PAIRS) {
  const category = { name, slug };
  CATEGORY_MAP.set(sourceSlug, category);
  CATEGORY_MAP.set(slug, category);
  CATEGORY_MAP.set(slugify(name), category);
}

export function normalizeImportCategory(value: string): NormalizedCategory {
  return findNormalizedImportCategory(value) ?? DEFAULT_CATEGORY;
}

export function findNormalizedImportCategory(value: string): NormalizedCategory | null {
  const key = slugify(value);
  if (!key) return null;
  return CATEGORY_MAP.get(key) ?? null;
}

export function normalizeImportCategories(values: string[], limit = 6): NormalizedCategory[] {
  const categories = values.map(normalizeImportCategory);
  const seen = new Set<string>();

  return categories
    .filter((category) => {
      if (seen.has(category.slug)) return false;
      seen.add(category.slug);
      return true;
    })
    .slice(0, limit);
}
